#!/bin/bash

CPU=$(top -bn1 | grep "Cpu" | awk '{print $2}')
MEM=$(free | awk '/Mem/ {printf("%.0f"), $3/$2 * 100}')
DISK=$(df / | awk 'END{print $5}' | sed 's/%//')

if [ "$CPU" -gt 80 ] || [ "$MEM" -gt 80 ] || [ "$DISK" -gt 80 ]; then
  echo "⚠️ ALERT: High Resource Usage" >> system_health.log
else
  echo "✅ System Healthy" >> system_health.log
fi
